services:
  go-app:
    build: .
    env_file:
    - .env
    ports:
    - 3000:3000
    volumes:
      - ./backend:/go/usr/src/app
    command: go run main.go
    
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5435:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "82:82"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go-app
      
volumes:
  postgres-db:
  